### ISSUE TITLE
Not a real issue but would be better

### ISSUE THREAD

**Issue by karaposu** [TKJElectronics/Balanduino#4]
Thank you for amazing code ! But there are some magic numbers i couldnt understand their origins.
for example :
 iTerm += cfg.I * 100.0f * error * dt;    why did you multiply with 100.0 ?  This is very important for me because i am working on pid project and your code looks very promising.

You can delete this issue. Just please add  answer as a comment in the pid_udate function of yours.Thanks a lot

**Comment by Lauszus** [comment]
@karaposu it was simply added so the PID values would be within the same order of magnitude in the Android app, so beginners would have an easier time tuning it.

For an alternative implementation, then you should check out the code for my flight controller: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/PID.c.
